[package]
name = "rls"
version = "0.1.0"
authors = ["zhijazi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
chrono = "0.4.10"
users = "0.9.1"
